### ISSUE TITLE
200 times redundancy

### ISSUE THREAD

**Issue by abhirammv** [sk-g/curveFittingMatlab#1]
Line 67 and 68: Why are the variables getting created with zeros 200 times? LOL.

**Comment by sk-g** [comment]
I think you are mentioning lines 67 and 68 from sdfg.m

```
k_split_cost=zeros(N_iter,1);
ktar_data=zeros(20,1);
```
It is a mistake to have them in the for loop but because it is not overwriting any data I don't see it as a bug or an issue that gives wrong results but would definitely make the run code run faster by a ms.
